const storageNews = [
  [
    {
      id: 1,
      image: require("./assets/img/presidents.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: " ed  prin nting and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 2,
      image: require("./assets/img/trees.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 08, 2022",
      views: 998,
    },
    {
      id: 3,
      image: require("./assets/img/presidents.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 4,
      image: require("./assets/img/presidents.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 5,
      image: require("./assets/img/presidents.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 6,
      image: require("./assets/img/trees.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
  ],
  [
    {
      id: 7,
      image: require("./assets/img/office.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: " a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 8,
      image: require("./assets/img/presentation.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 9,
      image: require("./assets/img/office.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book..",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 10,
      image: require("./assets/img/presentation.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 11,
      image: require("./assets/img/office.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    {
      id: 12,
      image: require("./assets/img/presentation.png"),
      title: "STAT OF THE DAY: Lorem Ipsum...",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      date: "Dec 07, 2022",
      views: 978,
    },
    
  ],
];

export default storageNews;
